### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
cache_dir: /home/qiaoziqing/cache_models

### method
stage: sft
do_train: true
finetuning_type: lora
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
# dataset: cmedqa2,discmed,headqa,medmcqa,mlecqa,webmedqa
dataset: disclaw
template: qwen
seed: 42
data_seed: 42
cutoff_len: 2048
# max_samples: 2000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2.5_7B_Instruct_lora_disclaw
logging_steps: 20
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: epoch
# eval_steps: 500
